[package]
name = "olap-core"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.9"                                  # gRPC 实现库
prost = "0.11"                                 # Protocol Buffers 编解码库
tokio = { version = "1", features = ["full"] } # 异步运行时
# regex = "1.11.1"                               # 正则表达式库
nom = "7.1"                                     # 解析器组合库
# nom-regex = "0.1"
# lalrpop-util = "0.22.0"

[build-dependencies]
tonic-build = "0.9"
# # If you are supplying your own external lexer you can disable default features so that the built-in lexer feature is not included
# lalrpop = { version = "0.22.0", default-features = false }